<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc" style="margin-top: 1em;"><ul class="toc-item"><li><span><a href="#Get-an-Interactive-TensorFlow-Session" data-toc-modified-id="Get-an-Interactive-TensorFlow-Session-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Get an Interactive TensorFlow Session</a></span></li><li><span><a href="#Customary-Hello-TensorFlow-!!!" data-toc-modified-id="Customary-Hello-TensorFlow-!!!-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Customary Hello TensorFlow !!!</a></span></li><li><span><a href="#Constants" data-toc-modified-id="Constants-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Constants</a></span></li><li><span><a href="#Operations" data-toc-modified-id="Operations-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Operations</a></span></li><li><span><a href="#Placeholders" data-toc-modified-id="Placeholders-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Placeholders</a></span></li><li><span><a href="#Creating-Tensors-from-Existing-Objects" data-toc-modified-id="Creating-Tensors-from-Existing-Objects-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Creating Tensors from Existing Objects</a></span><ul class="toc-item"><li><span><a href="#0-Dimensional-Tensors-(Scalars)" data-toc-modified-id="0-Dimensional-Tensors-(Scalars)-6.1"><span class="toc-item-num">6.1&nbsp;&nbsp;</span>0-Dimensional Tensors (Scalars)</a></span></li><li><span><a href="#1-Dimensional-Tensors-(Vectors)" data-toc-modified-id="1-Dimensional-Tensors-(Vectors)-6.2"><span class="toc-item-num">6.2&nbsp;&nbsp;</span>1-Dimensional Tensors (Vectors)</a></span></li><li><span><a href="#2-Dimensional-Tensors-(Matrices)" data-toc-modified-id="2-Dimensional-Tensors-(Matrices)-6.3"><span class="toc-item-num">6.3&nbsp;&nbsp;</span>2-Dimensional Tensors (Matrices)</a></span></li><li><span><a href="#3-Dimensional-Tensors" data-toc-modified-id="3-Dimensional-Tensors-6.4"><span class="toc-item-num">6.4&nbsp;&nbsp;</span>3-Dimensional Tensors</a></span></li></ul></li><li><span><a href="#Variables" data-toc-modified-id="Variables-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Variables</a></span></li><li><span><a href="#Creating-Tensors-from-Library-Functions" data-toc-modified-id="Creating-Tensors-from-Library-Functions-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>Creating Tensors from Library Functions</a></span></li><li><span><a href="#Close-the-interactive-session" data-toc-modified-id="Close-the-interactive-session-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>Close the interactive session</a></span></li><li><span><a href="#Computation-Graphs" data-toc-modified-id="Computation-Graphs-10"><span class="toc-item-num">10&nbsp;&nbsp;</span>Computation Graphs</a></span><ul class="toc-item"><li><span><a href="#Building-and-Running-simple-computation-graph" data-toc-modified-id="Building-and-Running-simple-computation-graph-10.1"><span class="toc-item-num">10.1&nbsp;&nbsp;</span>Building and Running simple computation graph</a></span></li><li><span><a href="#Graph-on-Compute-Devices" data-toc-modified-id="Graph-on-Compute-Devices-10.2"><span class="toc-item-num">10.2&nbsp;&nbsp;</span>Graph on Compute Devices</a></span></li><li><span><a href="#Executing-Graph-g-as-Default" data-toc-modified-id="Executing-Graph-g-as-Default-10.3"><span class="toc-item-num">10.3&nbsp;&nbsp;</span>Executing Graph g as Default</a></span></li></ul></li><li><span><a href="#TensorBoard" data-toc-modified-id="TensorBoard-11"><span class="toc-item-num">11&nbsp;&nbsp;</span>TensorBoard</a></span></li></ul></div>

# TensorFlow 101 <a class="tocSkip">

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tf.__version__

'1.15.5'

# Get an Interactive TensorFlow Session 

In [3]:
tfs = tf.InteractiveSession()

# Customary Hello TensorFlow !!!

In [4]:
hello = tf.constant("Hello TensorFlow !!")
print(tfs.run(hello))

b'Hello TensorFlow !!'


# Constants

```python
tf.constant(
    value,
    dtype=None,
    shape=None,
    name='Const',
    verify_shape=False
)
```

In [5]:
c1 = tf.constant(5, name='x')
c2 = tf.constant(6.0, name='y')
c3 = tf.constant(7.0, tf.float32, name='z')
print('c1 (x): ', c1)
print('c2 (y): ', c2)
print('c3 (z): ', c3)

c1 (x):  Tensor("x:0", shape=(), dtype=int32)
c2 (y):  Tensor("y:0", shape=(), dtype=float32)
c3 (z):  Tensor("z:0", shape=(), dtype=float32)


In [6]:
print('run([c1,c2,c3]) : ', tfs.run([c1, c2, c3]))

run([c1,c2,c3]) :  [5, 6.0, 7.0]


In [7]:
type(c1)

tensorflow.python.framework.ops.Tensor

# Operations

In [8]:
op1 = tf.add(c2, c3)
op2 = tf.multiply(c2, c3)
print('op1 : ', op1)
print('op2 : ', op2)

op1 :  Tensor("Add:0", shape=(), dtype=float32)
op2 :  Tensor("Mul:0", shape=(), dtype=float32)


In [9]:
print('run(op1) : ', tfs.run(op1))
print('run(op2) : ', tfs.run(op2))

run(op1) :  13.0
run(op2) :  42.0


In [10]:
# Note type is still considered Tensor here (after doing ops on it)
type(op1)

tensorflow.python.framework.ops.Tensor

In [11]:
type(tfs.run(op1))

numpy.float32

# Placeholders

```python
tf.placeholder(
    dtype,
    shape=None,
    name=None
)
```

In [12]:
p1 = tf.placeholder(tf.float32)
p2 = tf.placeholder(tf.float32)
print('p1 : ', p1)
print('p2 : ', p2)

p1 :  Tensor("Placeholder:0", dtype=float32)
p2 :  Tensor("Placeholder_1:0", dtype=float32)


In [13]:
op4 = p1 * p2  # shorthand for tf.multiply(p1, p2)

In [14]:
print(type(p1))
print(type(op4))

<class 'tensorflow.python.framework.ops.Tensor'>
<class 'tensorflow.python.framework.ops.Tensor'>


In [15]:
print('run(op4, {p1: 2.0, p2: 3.0}) : ', tfs.run(op4, {p1: 2.0, p2: 3.0}))  # <-- feed_dict

run(op4, {p1: 2.0, p2: 3.0}) :  6.0


In [16]:
print('run(op4, feed_dict = {p1: 3.0, p2: 4.0}) : ', 
      tfs.run(op4, feed_dict={p1: 3.0, p2: 4.0}))

run(op4, feed_dict = {p1: 3.0, p2: 4.0}) :  12.0


In [17]:
print('run(op4, feed_dict={p1: [2.0,3.0,4.0], p2: [3.0,4.0,5.0]}):',
      tfs.run(op4, feed_dict={p1: [2.0, 3.0, 4.0], p2: [3.0, 4.0, 5.0]}))

run(op4, feed_dict={p1: [2.0,3.0,4.0], p2: [3.0,4.0,5.0]}): [ 6. 12. 20.]


In [18]:
# ^ Note above that the Placeholder doesn't *necessarily* define a shape - we can potentially feed different shape tensors into it.

# Creating Tensors from Existing Objects

```python
tf.convert_to_tensor(
    value,
    dtype=None,
    name=None,
    preferred_dtype=None
)
```

## 0-Dimensional Tensors (Scalars)

In [19]:
tf_t = tf.convert_to_tensor(5.0, dtype=tf.float64)

print('tf_t : ', tf_t)
print('run(tf_t) : \n', tfs.run(tf_t))

tf_t :  Tensor("Const_1:0", shape=(), dtype=float64)
run(tf_t) : 
 5.0


## 1-Dimensional Tensors (Vectors)

In [20]:
a1dim = np.array([1, 2, 3, 4, 5.99])
print("a1dim Shape : ", a1dim.shape)

tf_t = tf.convert_to_tensor(a1dim, dtype=tf.float64)

print('tf_t : ', tf_t)
print('tf_t.shape: ', tf_t.shape)
print('tf_t[0] : ', tf_t[0])
print('tf_t[0] : ', tf_t[2])
print('run(tf_t) : \n', tfs.run(tf_t))

a1dim Shape :  (5,)
tf_t :  Tensor("Const_2:0", shape=(5,), dtype=float64)
tf_t.shape:  (5,)
tf_t[0] :  Tensor("strided_slice:0", shape=(), dtype=float64)
tf_t[0] :  Tensor("strided_slice_1:0", shape=(), dtype=float64)
run(tf_t) : 
 [1.   2.   3.   4.   5.99]


## 2-Dimensional Tensors (Matrices)

In [21]:
a2dim = np.array(
    [
        (1, 2, 3, 4, 5.99),
        (2, 3, 4, 5, 6.99),
        (3, 4, 5, 6, 7.99)
    ]
)
print("a2dim Shape : ", a2dim.shape)

tf_t = tf.convert_to_tensor(a2dim, dtype=tf.float64)

print('tf_t : ', tf_t)
print('tf_t.shape : ', tf_t.shape)
print('tf_t[0][0] : ', tf_t[0][0])
print('tf_t[1][2] : ', tf_t[1][2])
print('run(tf_t) : \n', tfs.run(tf_t))

a2dim Shape :  (3, 5)
tf_t :  Tensor("Const_3:0", shape=(3, 5), dtype=float64)
tf_t.shape :  (3, 5)
tf_t[0][0] :  Tensor("strided_slice_3:0", shape=(), dtype=float64)
tf_t[1][2] :  Tensor("strided_slice_5:0", shape=(), dtype=float64)
run(tf_t) : 
 [[1.   2.   3.   4.   5.99]
 [2.   3.   4.   5.   6.99]
 [3.   4.   5.   6.   7.99]]


## 3-Dimensional Tensors

In [22]:
a3dim = np.array(
    [
        [
            [1, 2],
            [3, 4],
        ],
        [
            [5, 6],
            [7, 8],
        ]
    ]
)
print("a3dim Shape : ", a3dim.shape)

tf_t = tf.convert_to_tensor(a3dim, dtype=tf.float64)

print('tf_t : ', tf_t)
print('tf_t.shape : ', tf_t.shape)
print('tf_t[0][0][0] : ', tf_t[0][0][0])
print('tf_t[1][1][1] : ', tf_t[1][1][1])
print('run(tf_t) : \n', tfs.run(tf_t))

a3dim Shape :  (2, 2, 2)
tf_t :  Tensor("Const_4:0", shape=(2, 2, 2), dtype=float64)
tf_t.shape :  (2, 2, 2)
tf_t[0][0][0] :  Tensor("strided_slice_8:0", shape=(), dtype=float64)
tf_t[1][1][1] :  Tensor("strided_slice_11:0", shape=(), dtype=float64)
run(tf_t) : 
 [[[1. 2.]
  [3. 4.]]

 [[5. 6.]
  [7. 8.]]]


# Variables

* `tf.placeholder` defines input data that does not change over time. 
* `tf.Variable` defines variable values that are modified over time.
* `tf.placeholder` does not need an initial value at the time of definition.
* `tf.Variable` needs an initial value at the time of definition

In [23]:
# Assume Linear Model y = w * x + b
# Define model parameters
w = tf.Variable([.3], tf.float32)
b = tf.Variable([-.3], tf.float32)
# Define model input and output
x = tf.placeholder(tf.float32)
y = w * x + b

print("w:", w)
print("x:", x)
print("b:", b)
print("y:", y)

w: <tf.Variable 'Variable:0' shape=(1,) dtype=float32_ref>
x: Tensor("Placeholder_2:0", dtype=float32)
b: <tf.Variable 'Variable_1:0' shape=(1,) dtype=float32_ref>
y: Tensor("add_1:0", dtype=float32)


In [24]:
# Note the "_ref" in dtype of Variables.

In [25]:
# initialize and print the variable y
tf.global_variables_initializer().run()  # Alternatively: tfs.run( tf.global_variables_initializer() )
print('run(y, {x: [1,2,3,4]}) : ', tfs.run(y, {x: [1, 2, 3, 4]}))

run(y, {x: [1,2,3,4]}) :  [0.         0.3        0.6        0.90000004]


In [26]:
# You can also use the tf.variables_initializer() function to initialize only a set of variables.

# Creating Tensors from Library Functions

In [27]:
a = tf.zeros((100,))
print(tfs.run(a))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


In [28]:
b = tf.fill((2, 4), value=7., name="b")
print(b)
print(tfs.run(b))

Tensor("b:0", shape=(2, 4), dtype=float32)
[[7. 7. 7. 7.]
 [7. 7. 7. 7.]]


In [29]:
r = tf.range(1, 91, delta=10)
print(r)
print(tfs.run(r))

Tensor("range:0", shape=(9,), dtype=int32)
[ 1 11 21 31 41 51 61 71 81]


In [30]:
# From distribution.
tf.set_random_seed(12345)
n = tf.random_normal(
    (3, 2), 
    mean=0, 
    stddev=3.0, 
    dtype=tf.float64, 
    seed=777,  # NOTE THIS SEED HERE! 
    name="n"
)

print(n)
print(tfs.run(n))

Tensor("n:0", shape=(3, 2), dtype=float64)
[[-1.36682311  2.06684499]
 [-0.18542505 -3.43506363]
 [-0.44697834  0.39600509]]


#### On Random Seeds in TF1
The distributions generated are affected by the **graph-level** or the **operation-level** seed. 

* The **graph-level seed** is set using `tf.set_random_seed()`.
* \[⚠️\] The **operation-level seed** is given *as the argument seed in **all of the random distribution functions***. 

If no seed is specified, then a random seed is used.

# Variable Reuse

The function `tf.get_variable()` returns the existing variable with the same name if it exists, and creates the variable with the specified shape and initializer if it does not exist.

In [32]:
w = tf.get_variable(name='w', dtype=tf.float32, initializer=[.3])
b = tf.get_variable(name='b', dtype=tf.float32, initializer=[-.3])

🛑 **Info in the book here is out of date!**

Read this article instead: https://medium.com/@hideyuki/what-does-variable-reuse-mean-in-tensorflow-40e86535026b

Covers `scope`, `reuse`, `AUTO_REUSE`.

### ⚠️ See my notebook: [my-nb-01_Variable_Reuse.ipynb](./my-nb-01_Variable_Reuse.ipynb)

# Close the interactive session

In [33]:
tfs.close()

# Computation Graphs

> A computation graph is made up of **nodes** and **edges**. Each node represents an operation (`tf.Operation`) and each edge represents a tensor (`tf.Tensor`) that gets transferred between the nodes.

A program in TensorFlow is basically a computation graph. 

You create the graph with nodes representing:
* variables, 
* constants, 
* placeholders, 
* and operations 

and feed it to TensorFlow. 

TensorFlow finds the first nodes that it can fire or execute. The firing of these nodes results in the firing of other nodes, and so on.

Thus, TensorFlow programs are made up of two kinds of operations on computation graphs:
* Building the computation graph
* Running the computation graph

<br/>

TensorFlow comes with a **default graph**. Unless another graph is explicitly specified, *a new node gets implicitly added to the default graph*. We can get explicit access to the default graph using the following command: `graph = tf.get_default_graph()`

For example, if we want to define three inputs and add them to produce output, we can represent it using the following computation graph:

![ComputationGraph](./ComputationGraph.png)

In TensorFlow, the add operation in the preceding image would correspond to the code `y = tf.add( x1 + x2 + x3 )`.

As we create the variables, constants, and placeholders, they get added to the graph. Then we create a **session** object to execute the operation objects and evaluate the tensor objects.

## Building and Running simple computation graph

In [36]:
# Assume Linear Model y = w * x + b
# Define model parameters
w = tf.Variable([.3], tf.float32)
b = tf.Variable([-.3], tf.float32)

# Define model input and output
x = tf.placeholder(tf.float32)
y = w * x + b

with tf.Session() as tfs:  # NOTE: the with block will automatically call tfs.close() at the end.
    
    # initialize and print the variable y
    tf.global_variables_initializer().run()
    output = tfs.run(y, feed_dict={x: [1, 2, 3, 4]})

    print('output : ', output)

output :  [0.         0.3        0.6        0.90000004]


# Order of execution and lazy loading

The nodes are executed in the order of dependency. If node $a$ depends on node $b$, then $a$ will be executed before $b$ when the execution of $b$ is requested. 

A node is not executed unless either the node itself or another node depending on it is not requested for execution. This is
also known as lazy loading; namely, the node objects are not created and initialized until they are needed.

Sometimes, you may want to control the order in which the nodes are executed in a graph. This can be achieved with the `tf.Graph.control_dependencies()` function. For example, if the graph has nodes $a$, $b$, $c$, and $d$ and you want to execute $c$ and $d$ before $a$ and $b$, then use the following statement:
```python
with graph_variable.control_dependencies([c, d]):
    # other statements here
```
This makes sure that any node in the preceding with block is executed only after nodes $c$ and $d$ have been executed.

## Graph on Compute Devices

In [37]:
from tensorflow.python.client import device_lib

print(device_lib.list_local_devices())

[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 17202171288944793001
, name: "/device:XLA_CPU:0"
device_type: "XLA_CPU"
memory_limit: 17179869184
locality {
}
incarnation: 6020470525130642112
physical_device_desc: "device: XLA_CPU device"
, name: "/device:XLA_GPU:0"
device_type: "XLA_GPU"
memory_limit: 17179869184
locality {
}
incarnation: 18132847180197464680
physical_device_desc: "device: XLA_GPU device"
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 89653248
locality {
  bus_id: 1
  links {
  }
}
incarnation: 17621415796009797239
physical_device_desc: "device: 0, name: GeForce RTX 2080, pci bus id: 0000:01:00.0, compute capability: 7.5"
]


#### In their case, the output was:
```python
[name: "/cpu:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 12445270569278384213
, name: "/gpu:0"
device_type: "GPU"
memory_limit: 25628672
locality {
  bus_id: 1
}
incarnation: 5284662930836416221
physical_device_desc: "device: 0, name: GeForce GT 750M, pci bus id: 0000:01:00.0"
]
```

The devices in TensorFlow are identified with the string `/device:<device_type>:<device_idx>` . 

One thing to note about the above output is that it shows only one CPU, whereas our computer has 8 CPUs. The reason for that is TensorFlow implicitly distributes the code across the CPU units and thus by default `CPU:0` denotes all the CPU's available to TensorFlow. When TensorFlow starts executing graphs, it runs the independent paths within each graph in a separate thread, with each thread running on a separate CPU. 

We can restrict the number of threads used for this purpose by changing the number of `inter_op_parallelism_threads`. Similarly, if within an independent path, an operation is capable of running on multiple threads, TensorFlow will launch that specific operation on multiple threads. The number of threads in this pool can be changed by setting the number of `intra_op_parallelism_threads`.

### Placing graph nodes on *specific compute devices*

In [68]:
tf.reset_default_graph()

# Define model parameters
w = tf.get_variable(name='w', initializer=[.3], dtype=tf.float32)
b = tf.get_variable(name='b', initializer=[-.3], dtype=tf.float32)
# Define model input and output
x = tf.placeholder(name='x', dtype=tf.float32)
y = w * x + b

# Enable LOGGING of device placement.
config = tf.ConfigProto()
config.log_device_placement = True

with tf.Session(config=config) as tfs:
    # initialize and print the variable y
    tfs.run(tf.global_variables_initializer())
    print('output', tfs.run(y, {x: [1, 2, 3, 4]}))

Device mapping:
/job:localhost/replica:0/task:0/device:XLA_CPU:0 -> device: XLA_CPU device
/job:localhost/replica:0/task:0/device:XLA_GPU:0 -> device: XLA_GPU device
/job:localhost/replica:0/task:0/device:GPU:0 -> device: 0, name: GeForce RTX 2080, pci bus id: 0000:01:00.0, compute capability: 7.5

output [0.         0.3        0.6        0.90000004]


**^ Confirmed on CPU**

### To see the device placement, look at the TERMINAL (not printed within jupyter)!

In [69]:
tf.reset_default_graph()

with tf.device('/device:CPU:0'):  # <--- `tf.device()` context manager.
    # Define model parameters
    w = tf.get_variable(name='w', initializer=[.3], dtype=tf.float32)
    b = tf.get_variable(name='b', initializer=[-.3], dtype=tf.float32)
    # Define model input and output
    x = tf.placeholder(name='x', dtype=tf.float32)
    y = w * x + b

config = tf.ConfigProto()
config.log_device_placement = True

with tf.Session(config=config) as tfs:
    # initialize and print the variable y
    tfs.run(tf.global_variables_initializer())
    print('output', tfs.run(y, {x: [1, 2, 3, 4]}))

Device mapping:
/job:localhost/replica:0/task:0/device:XLA_CPU:0 -> device: XLA_CPU device
/job:localhost/replica:0/task:0/device:XLA_GPU:0 -> device: XLA_GPU device
/job:localhost/replica:0/task:0/device:GPU:0 -> device: 0, name: GeForce RTX 2080, pci bus id: 0000:01:00.0, compute capability: 7.5

output [0.         0.3        0.6        0.90000004]


**^ Confirmed on GPU**

In [70]:
tf.reset_default_graph()

with tf.device('/device:CPU:0'):
    # Define model parameters
    w = tf.get_variable(name='w', initializer=[.3], dtype=tf.float32)
    b = tf.get_variable(name='b', initializer=[-.3], dtype=tf.float32)
    # Define model input and output
    x = tf.placeholder(name='x', dtype=tf.float32)

with tf.device('/device:GPU:0'):  # <-- Place y (which comes from w, x and b) on a DIFFERENT device!!!
    y = w * x + b

config = tf.ConfigProto()
config.log_device_placement = True

with tf.Session(config=config) as tfs:
    # initialize and print the variable y
    tfs.run(tf.global_variables_initializer())
    print('output', tfs.run(y, {x: [1, 2, 3, 4]}))

Device mapping:
/job:localhost/replica:0/task:0/device:XLA_CPU:0 -> device: XLA_CPU device
/job:localhost/replica:0/task:0/device:XLA_GPU:0 -> device: XLA_GPU device
/job:localhost/replica:0/task:0/device:GPU:0 -> device: 0, name: GeForce RTX 2080, pci bus id: 0000:01:00.0, compute capability: 7.5

output [0.         0.3        0.6        0.90000004]


**^ Confirmed some on CPU then on GPU**

### Simple placement
TensorFlow follows these simple rules, also known as the simple placement, for placing the variables on the devices:
```bash
If the graph was previously run,
    then the node is left on the device where it was placed earlier
Else If the tf.device() block is used,
    then the node is placed on the specified device
Else If the GPU is present
    then the node is placed on the first available GPU
Else If the GPU is not present
    then the node is placed on the CPU
```

### Dynamic placement
The `tf.device()` can also be **passed a function name** instead of a device string. 

In such case, the function must return the device string. 

This feature allows complex algorithms for placing the variables on different devices. For example, TensorFlow provides a round robin device setter in `tf.train.replica_device_setter()`.

### Soft placement
When you place a TensorFlow operation on the GPU, the TF must have the GPU implementation of that operation, known as the *kernel*. If the kernel is not present then the placement results in run-time error. Also if the GPU device you requested does not exist, you will get a run-time error. The best way to handle such errors is to allow the operation to be placed on the CPU if requesting the GPU device results in n error. This can be achieved by setting the following config value:
```python
config.allow_soft_placement = True
```

# GPU memory handling

When you start running the TensorFlow session, by default it grabs all of the GPU memory, even if you place the operations and variables only on one GPU in a multi-GPU system. If you try to run another session at the same time, you will get out of memory error. This can be solved in multiple ways:

* For multi-GPU systems, set the environment variable `CUDA_VISIBLE_DEVICES=<list of device idx>`
```python
os.environ['CUDA_VISIBLE_DEVICES']='0'
```
The code executed after this setting will be able to grab all of the memory of only the visible GPU.

* When you do not want the session to grab all of the memory of the GPU, then you can use the config option `per_process_gpu_memory_fraction` to allocate a percentage of memory:
```python
config.gpu_options.per_process_gpu_memory_fraction = 0.5
```
This will allocate 50% of the memory of all the GPU devices.

* You can also combine both of the above strategies, i.e. make only a percentage along with making only some of the GPU visible to the process.

* You can also limit the TensorFlow process to grab only the minimum required memory at the start of the process. As the process executes further, you can set a config option to allow the growth of this memory.
```python
config.gpu_options.allow_growth = True
```
This option only allows for the allocated memory to grow, **but the memory is never released back**.

## Executing Graph g as Default

### Note on Multople Graphs
You can create your own graphs separate from the default graph and execute them in a session. However, creating and **executing multiple graphs is not recommended**, as it has the following disadvantages:
* Creating and using multiple graphs in the same program would require multiple TensorFlow sessions and each session would consume heavy resources
* You cannot directly pass data in between graphs

Hence, the recommended approach is to have **multiple *subgraphs*** in a single graph.

In [72]:
# Here is an example where we create our own graph, g , and execute it as the default graph:

g = tf.Graph()  # <-- NOTE.

with g.as_default():  # <-- NOTE.
    w = tf.Variable([.3], tf.float32)
    b = tf.Variable([-.3], tf.float32)
    x = tf.placeholder(tf.float32)
    y = w * x + b

with tf.Session(graph=g) as tfs:
    tf.global_variables_initializer().run()
    output = tfs.run(y, {x: [1, 2, 3, 4]})

print('output : ', output)

output :  [0.         0.3        0.6        0.90000004]


# TensorBoard

> TensorBoard:
> 1. visualizes computation graph structure, 
> 2. provides statistical analysis, 
> 3. plots the values captured as summaries during the execution of computation graphs.

In [76]:
tf.reset_default_graph()

import tensorflow as tf
import numpy as np

# Assume Linear Model y = w * x + b

# Define model parameters
w = tf.Variable([.3], name='w', dtype=tf.float32)
b = tf.Variable([-.3], name='b', dtype=tf.float32)

# Define model input and output
x = tf.placeholder(name='x', dtype=tf.float32)
y = w * x + b

with tf.Session() as tfs:
    tf.global_variables_initializer().run()
    writer = tf.summary.FileWriter('tflogs', tfs.graph)  # <-- Create tf.summary.FileWriter that would create the output in the tflogs folder with the events from the default graph.
    print('run(y, feed_dict={x: 3} : ', tfs.run(y, feed_dict={x: 3}))

run(y, feed_dict={x: 3} :  [0.6]


#### execute: `tensorboard --logdir='tflogs'`

![TensorBoardGraph](./TensorBoardGraph.png)

# TensorBoard workflow (advanced)

TensorBoard works by reading log files generated by TensorFlow. Thus, we need to modify the programming model defined here to incorporate additional operation nodes that would produce the information in the logs that we want to visualize using TensorBoard. The programming model or the flow of programs with TensorBoard can be generally stated as follows:

1. Create the computational graph as usual.

2. Create summary nodes. Attach summary operations from the `tf.summary` package to the nodes that output the values that you wish to collect and analyze.

3. Run the summary nodes along with running your model nodes. Generally, you would use the convenience function, `tf.summary.merge_all()`, to merge all the summary nodes into one summary node. Then executing this merged node would basically execute all the summary nodes. The merged summary node produces a serialized `Summary` ProtocolBuffers object containing the union of all the summaries.

4. Write the event logs to disk by passing the `Summary` ProtocolBuffers object to a `tf.summary.FileWriter` object.

5. Start TensorBoard and analyze the visualized data. 

**In the above section, we did not create summary nodes but used TensorBoard in a very simple way.** 
We will cover the advanced usage of TensorBoard later in this book.